---
version: '3.9'
services:
  cache:
    image: gomods/athens:latest
    network_mode: host
    environment:
    - ATHENS_STORAGE_TYPE=disk
    - ATHENS_DISK_STORAGE_ROOT=/data
    - ATHENS_GO_BINARY_ENV_VARS=GOPROXY=https://proxy.golang.org,direct
    volumes:
    - ./data:/data
